image: php:7.4

before_script:
  - bash ci/docker_install.sh > /dev/null

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: $STAGING_URL
  script:
    - echo "Staging"
    - ssh root@192.168.1.11 "cd /root/sites/$STAGING_URL && git checkout staging && git pull origin main && chmod a+x *.sh && exit"
  only:
    - staging

deploy-production:
  stage: deploy
  environment:
    name: production
    url: $PRODUCTION_URL
  script:
    - echo "Production"
    - ssh root@192.168.1.11 "cd /root/sites/$PRODUCTION_URL && git checkout production && git pull origin main && chmod a+x *.sh && exit"
  only:
    - production