image: php:7.4

before_script:
  - bash ci/docker_install.sh > /dev/null

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: staging.jtiong.dev
  script:
    - echo "Staging"
    - ssh root@192.168.1.11 "cd /root/sites/staging.jtiong.dev && git checkout main && git pull origin main && chmod a+x *.sh && exit"
  only:
    - main

deploy-production:
  stage: deploy
  environment:
    name: production
    url: jtiong.dev
  script:
    - echo "Production"
    - ssh root@192.168.1.11 "cd /root/sites/jtiong.dev && git checkout production && git pull origin production && chmod a+x *.sh && exit"
  only:
    - production