version: '3.3'

services:
  jtiong.dev:
    image: php:7.4
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - core_db
    container_name: jtiong.dev
    volumes:
      - ../code:/var/www/html
      - ../data/uploads:/var/www/html/uploads
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ../data/logs/error.log:/var/www/error.log
      - ../data/logs/access.log:/var/www/access.log
    environment:
      VIRTUAL_HOST: jtiong.dev, www.jtiong.dev
      LETSENCRYPT_HOST: jtiong.dev
      LETSENCRYPT_EMAIL: j.tiong.notifier@gmail.com
    restart: always

networks:
    default:
      name: proxy
